GET https://pizza-api.projectcodex.net/api/pizza-cart/:JYzmSKO4Ky/get
//JYzmSKO4Ky


###
POST https://pizza-api.projectcodex.net/api/pizzas/api/pizza-cart/add/
content-type: application/json

{
	"cart_code" : "JYzmSKO4Ky",
	"pizza_id" : 23

}

